// <auto-generated />
using HitExercise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HitExercise.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HitExercise.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryCode = 110,
                            Name = "Food-Supply"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryCode = 120,
                            Name = "Room-Equipment"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryCode = 130,
                            Name = "Electronic-Equipment"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryCode = 140,
                            Name = "Medical-Equipment"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryCode = 150,
                            Name = "Garden-Equipment"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryCode = 160,
                            Name = "Pool-Equipment"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryCode = 170,
                            Name = "FireSecurity-Equipment"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryCode = 180,
                            Name = "Plumber-Equipment"
                        });
                });

            modelBuilder.Entity("HitExercise.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryCode = 1210,
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryCode = 1220,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryCode = 1230,
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryCode = 1240,
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryCode = 1250,
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryCode = 1260,
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryCode = 1270,
                            Name = "Egypt"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryCode = 1280,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryCode = 1290,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 10,
                            CountryCode = 1300,
                            Name = "Greece"
                        },
                        new
                        {
                            CountryId = 11,
                            CountryCode = 1310,
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 12,
                            CountryCode = 1320,
                            Name = "Italy"
                        },
                        new
                        {
                            CountryId = 13,
                            CountryCode = 1330,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 14,
                            CountryCode = 1340,
                            Name = "Malaysia"
                        },
                        new
                        {
                            CountryId = 15,
                            CountryCode = 1350,
                            Name = "Morroco"
                        },
                        new
                        {
                            CountryId = 16,
                            CountryCode = 1360,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 17,
                            CountryCode = 1370,
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryId = 18,
                            CountryCode = 1380,
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryId = 19,
                            CountryCode = 1390,
                            Name = "Russia"
                        },
                        new
                        {
                            CountryId = 20,
                            CountryCode = 1400,
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = 21,
                            CountryCode = 1410,
                            Name = "Sweeden"
                        },
                        new
                        {
                            CountryId = 22,
                            CountryCode = 1420,
                            Name = "Turkey"
                        },
                        new
                        {
                            CountryId = 23,
                            CountryCode = 1430,
                            Name = "USA"
                        },
                        new
                        {
                            CountryId = 24,
                            CountryCode = 1440,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 25,
                            CountryCode = 1450,
                            Name = "Venezuela"
                        });
                });

            modelBuilder.Entity("HitExercise.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Afm")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CountryId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("HitExercise.Models.Supplier", b =>
                {
                    b.HasOne("HitExercise.Models.Category", "Category")
                        .WithMany("Suppliers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HitExercise.Models.Country", "Country")
                        .WithMany("Suppliers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HitExercise.Models.Category", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("HitExercise.Models.Country", b =>
                {
                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
